export type Deposit = { date: string; description: string; type: string; category: string; amount: number }
export type CheckingExp = { date: string; checkNum: string; description: string; category: string; amount: number }
export type CCTx = { postDate: string; txDate: string; account: string; description: string; category: string; amount: number; personal: boolean }

export const deposits: Deposit[] = [
  { date: '04/01/2026', description: 'EPX Merchant Settlement',                      type: 'EPX Settlement',  category: 'Sales - Card Payments',        amount: 870.01 },
  { date: '04/01/2026', description: 'Zelle - Sandra Castillo',                       type: 'Zelle Received',  category: 'Sales - Zelle Payments',       amount: 840.00 },
  { date: '04/02/2026', description: 'EPX Merchant Settlement',                      type: 'EPX Settlement',  category: 'Sales - Card Payments',        amount: 730.01 },
  { date: '04/02/2026', description: 'Zelle - Julien Kenderson',                      type: 'Zelle Received',  category: 'Sales - Zelle Payments',       amount: 300.00 },
  { date: '04/02/2026', description: 'Zelle - Cam DX Corp',                           type: 'Zelle Received',  category: 'Sales - Zelle Payments',       amount: 150.00 },
  { date: '04/03/2026', description: 'EPX Merchant Settlement',                      type: 'EPX Settlement',  category: 'Sales - Card Payments',        amount: 715.02 },
  { date: '04/03/2026', description: 'Zelle - Zamora Valenzuela',                     type: 'Zelle Received',  category: 'Sales - Zelle Payments',       amount: 240.00 },
  { date: '04/06/2026', description: 'Mobile Check Deposit',                          type: 'Check Deposit',   category: 'Sales - Check Payments',       amount: 3160.00 },
  { date: '04/06/2026', description: 'Zelle - Farhat Mojaddidi',                      type: 'Zelle Received',  category: 'Sales - Zelle Payments',       amount: 2050.00 },
  { date: '04/06/2026', description: 'Zelle - Yusuf Anas',                            type: 'Zelle Received',  category: 'Sales - Zelle Payments',       amount: 870.00 },
  { date: '04/06/2026', description: 'EPX Merchant Settlement',                      type: 'EPX Settlement',  category: 'Sales - Card Payments',        amount: 635.01 },
  { date: '04/06/2026', description: 'Zelle - Direct Autohaus',                       type: 'Zelle Received',  category: 'Sales - Zelle Payments',       amount: 320.00 },
  { date: '04/06/2026', description: 'EPX Merchant Settlement',                      type: 'EPX Settlement',  category: 'Sales - Card Payments',        amount: 180.00 },
  { date: '04/07/2026', description: 'EPX Merchant Settlement',                      type: 'EPX Settlement',  category: 'Sales - Card Payments',        amount: 545.02 },
  { date: '04/07/2026', description: 'Zelle - Carlos Escobar Padron',                 type: 'Zelle Received',  category: 'Sales - Zelle Payments',       amount: 240.00 },
  { date: '04/08/2026', description: 'EPX Merchant Settlement',                      type: 'EPX Settlement',  category: 'Sales - Card Payments',        amount: 75.00 },
  { date: '04/09/2026', description: 'EPX Merchant Settlement',                      type: 'EPX Settlement',  category: 'Sales - Card Payments',        amount: 75.00 },
  { date: '04/10/2026', description: 'Amazon Refund',                                 type: 'Refund',          category: 'Other - Refund',               amount: 387.37 },
  { date: '04/13/2026', description: 'Mobile Check Deposit',                          type: 'Check Deposit',   category: 'Sales - Check Payments',       amount: 1320.00 },
  { date: '04/13/2026', description: 'EPX Merchant Settlement',                      type: 'EPX Settlement',  category: 'Sales - Card Payments',        amount: 435.01 },
  { date: '04/14/2026', description: 'Return of Posted Check',                        type: 'Bank Return',     category: 'Non-Operating - Bank Return',  amount: 1976.32 },
  { date: '04/14/2026', description: 'Overdraft Protection Transfer',                 type: 'Bank Transfer',   category: 'Non-Operating - Transfer',     amount: 557.31 },
  { date: '04/14/2026', description: 'EPX Merchant Settlement',                      type: 'EPX Settlement',  category: 'Sales - Card Payments',        amount: 4310.13 },
  { date: '04/15/2026', description: 'EPX Merchant Settlement',                      type: 'EPX Settlement',  category: 'Sales - Card Payments',        amount: 815.02 },
  { date: '04/15/2026', description: 'Zelle - Cam DX Corp',                           type: 'Zelle Received',  category: 'Sales - Zelle Payments',       amount: 200.00 },
  { date: '04/16/2026', description: 'EPX Merchant Settlement',                      type: 'EPX Settlement',  category: 'Sales - Card Payments',        amount: 420.01 },
  { date: '04/17/2026', description: 'Zelle - Marco Castrosanchez (VW Atlas oil change)', type: 'Zelle Received', category: 'Sales - Zelle Payments',    amount: 290.00 },
  { date: '04/17/2026', description: 'EPX Merchant Settlement',                      type: 'EPX Settlement',  category: 'Sales - Card Payments',        amount: 280.00 },
  { date: '04/20/2026', description: 'EPX Merchant Settlement',                      type: 'EPX Settlement',  category: 'Sales - Card Payments',        amount: 1570.04 },
  { date: '04/20/2026', description: 'EPX Merchant Settlement',                      type: 'EPX Settlement',  category: 'Sales - Card Payments',        amount: 760.02 },
  { date: '04/20/2026', description: 'Zelle - Jorge Romero Pino',                     type: 'Zelle Received',  category: 'Sales - Zelle Payments',       amount: 280.00 },
  { date: '04/20/2026', description: 'Zelle - Faisal Anas',                           type: 'Zelle Received',  category: 'Sales - Zelle Payments',       amount: 70.00 },
  { date: '04/20/2026', description: 'Zelle - Carlos Calderon',                       type: 'Zelle Received',  category: 'Sales - Zelle Payments',       amount: 60.00 },
  { date: '04/21/2026', description: 'Zelle - Direct Autohaus (BMW/Audi sensors)',    type: 'Zelle Received',  category: 'Sales - Zelle Payments',       amount: 350.00 },
  { date: '04/21/2026', description: 'EPX Merchant Settlement',                      type: 'EPX Settlement',  category: 'Sales - Card Payments',        amount: 60.00 },
  { date: '04/21/2026', description: 'Zelle - Xdrive LLC',                            type: 'Zelle Received',  category: 'Sales - Zelle Payments',       amount: 50.00 },
  { date: '04/22/2026', description: 'EPX Merchant Settlement',                      type: 'EPX Settlement',  category: 'Sales - Card Payments',        amount: 775.01 },
  { date: '04/23/2026', description: 'EPX Merchant Settlement',                      type: 'EPX Settlement',  category: 'Sales - Card Payments',        amount: 795.02 },
  { date: '04/24/2026', description: 'EPX Merchant Settlement',                      type: 'EPX Settlement',  category: 'Sales - Card Payments',        amount: 1000.01 },
  { date: '04/24/2026', description: 'Zelle - Cam DX Corp',                           type: 'Zelle Received',  category: 'Sales - Zelle Payments',       amount: 100.00 },
  { date: '04/24/2026', description: 'Zelle - Omar Zurita',                           type: 'Zelle Received',  category: 'Sales - Zelle Payments',       amount: 50.00 },
  { date: '04/27/2026', description: 'EPX Merchant Settlement',                      type: 'EPX Settlement',  category: 'Sales - Card Payments',        amount: 1950.06 },
  { date: '04/27/2026', description: 'EPX Merchant Settlement',                      type: 'EPX Settlement',  category: 'Sales - Card Payments',        amount: 1433.03 },
  { date: '04/27/2026', description: 'Zelle - Victor Villegas',                       type: 'Zelle Received',  category: 'Sales - Zelle Payments',       amount: 100.00 },
  { date: '04/28/2026', description: 'EPX Merchant Settlement',                      type: 'EPX Settlement',  category: 'Sales - Card Payments',        amount: 1230.03 },
  { date: '04/29/2026', description: 'EPX Merchant Settlement',                      type: 'EPX Settlement',  category: 'Sales - Card Payments',        amount: 1215.04 },
  { date: '04/29/2026', description: 'Zelle - Jorge Ruiz (Lincoln)',                  type: 'Zelle Received',  category: 'Sales - Zelle Payments',       amount: 200.00 },
  { date: '04/29/2026', description: 'Zelle - Richard Prieto (tire patch)',           type: 'Zelle Received',  category: 'Sales - Zelle Payments',       amount: 70.00 },
  { date: '04/29/2026', description: 'Zelle - Julien Kenderson',                      type: 'Zelle Received',  category: 'Sales - Zelle Payments',       amount: 60.00 },
  { date: '04/30/2026', description: 'EPX Merchant Settlement',                      type: 'EPX Settlement',  category: 'Sales - Card Payments',        amount: 1060.02 },
  { date: '04/30/2026', description: 'Zelle - Motor Point LLC',                       type: 'Zelle Received',  category: 'Sales - Zelle Payments',       amount: 200.00 },
]

export const checkingExpenses: CheckingExp[] = [
  { date: '04/01/2026', checkNum: '',     description: 'Bank Monthly Maintenance Fee',        category: 'Bank Fees',                    amount: 16.00 },
  { date: '04/01/2026', checkNum: '',     description: 'Excess Transaction Fee',               category: 'Bank Fees',                    amount: 2.70 },
  { date: '04/01/2026', checkNum: '',     description: 'EPX Merchant Processing Fee',          category: 'Merchant Processing',          amount: 10.00 },
  { date: '04/01/2026', checkNum: '',     description: 'ADP 401k Contribution',                category: 'Payroll-401k',                 amount: 30.00 },
  { date: '04/01/2026', checkNum: '',     description: 'ADP Pay-By-Pay (Workers Comp)',        category: 'Payroll-Workers Comp',         amount: 86.75 },
  { date: '04/01/2026', checkNum: '4064', description: 'Tire Network — Tire Purchase',         category: 'Inventory-Tires',              amount: 600.00 },
  { date: '04/01/2026', checkNum: '4066', description: 'U.S. Auto Force — Parts',              category: 'Inventory-Parts & Supplies',   amount: 574.38 },
  { date: '04/01/2026', checkNum: '4068', description: 'Tire Co — Tire Purchase',              category: 'Inventory-Tires',              amount: 200.00 },
  { date: '04/03/2026', checkNum: '',     description: 'ADP Payroll Processing Fee',           category: 'Payroll-Processing Fees',      amount: 118.50 },
  { date: '04/03/2026', checkNum: '',     description: 'ADP Payroll Processing Fee',           category: 'Payroll-Processing Fees',      amount: 40.00 },
  { date: '04/03/2026', checkNum: '',     description: 'Toyota Financial — Vehicle Loan',      category: 'Vehicle-Loan',                 amount: 326.39 },
  { date: '04/03/2026', checkNum: '4069', description: 'Tire Outlet — Tire Purchase',          category: 'Inventory-Tires',              amount: 630.00 },
  { date: '04/06/2026', checkNum: '',     description: 'ADP Wage Pay — Payroll',               category: 'Payroll-Wages',                amount: 1976.32 },
  { date: '04/06/2026', checkNum: '',     description: 'ADP Tax Deposit',                      category: 'Payroll-Payroll Taxes',        amount: 607.68 },
  { date: '04/06/2026', checkNum: '',     description: 'Zelle to Teo — Labor/Supply',          category: 'Labor/Subcontractors',         amount: 200.00 },
  { date: '04/06/2026', checkNum: '',     description: 'Zelle to Juan Used Tires',             category: 'Inventory-Tires',              amount: 700.00 },
  { date: '04/06/2026', checkNum: '',     description: 'Gladly Coffee',                        category: 'Meals/Entertainment',          amount: 27.10 },
  { date: '04/06/2026', checkNum: '4070', description: 'Freedom — Parts Purchase',             category: 'Inventory-Parts & Supplies',   amount: 479.40 },
  { date: '04/07/2026', checkNum: '',     description: 'ADP 401k Contribution',                category: 'Payroll-401k',                 amount: 30.00 },
  { date: '04/07/2026', checkNum: '',     description: 'ADP Pay-By-Pay (Workers Comp)',        category: 'Payroll-Workers Comp',         amount: 166.69 },
  { date: '04/07/2026', checkNum: '',     description: 'FDMS Merchant Processing Fee',         category: 'Merchant Processing',          amount: 4.95 },
  { date: '04/07/2026', checkNum: '',     description: 'LGND SOCAL',                           category: 'Miscellaneous',                amount: 130.00 },
  { date: '04/08/2026', checkNum: '',     description: 'CC Payment — Card 6514',               category: 'Credit Card Payment',          amount: 1000.00 },
  { date: '04/08/2026', checkNum: '',     description: 'FDMS Merchant Processing Fee',         category: 'Merchant Processing',          amount: 37.71 },
  { date: '04/10/2026', checkNum: '',     description: 'ADP Payroll Processing Fee',           category: 'Payroll-Processing Fees',      amount: 134.50 },
  { date: '04/10/2026', checkNum: '4040', description: 'U.S. Auto Force — Parts',              category: 'Inventory-Parts & Supplies',   amount: 659.96 },
  { date: '04/13/2026', checkNum: '',     description: 'ADP Wage Pay — Payroll',               category: 'Payroll-Wages',                amount: 1976.32 },
  { date: '04/13/2026', checkNum: '',     description: 'ADP Tax Deposit',                      category: 'Payroll-Payroll Taxes',        amount: 607.68 },
  { date: '04/13/2026', checkNum: '',     description: 'ADP 401k Contribution',                category: 'Payroll-401k',                 amount: 30.00 },
  { date: '04/13/2026', checkNum: '',     description: 'AT&T Phone',                           category: 'Utilities-Phone',              amount: 244.89 },
  { date: '04/13/2026', checkNum: '4051', description: 'Tire Outlet — Tire Purchase',          category: 'Inventory-Tires',              amount: 1816.00 },
  { date: '04/13/2026', checkNum: '4061', description: 'Tire Outlet — Tire Purchase',          category: 'Inventory-Tires',              amount: 1216.00 },
  { date: '04/13/2026', checkNum: '4072', description: 'Basil Hosmer — Rent',                  category: 'Rent',                         amount: 3400.00 },
  { date: '04/13/2026', checkNum: '4073', description: 'Tire Outlet — Tire Purchase',          category: 'Inventory-Tires',              amount: 1080.00 },
  { date: '04/13/2026', checkNum: '4074', description: 'U.S. Auto Force — Parts',              category: 'Inventory-Parts & Supplies',   amount: 120.12 },
  { date: '04/13/2026', checkNum: '4075', description: 'GW — Labor',                           category: 'Labor/Subcontractors',         amount: 110.00 },
  { date: '04/14/2026', checkNum: '',     description: 'ADP Pay-By-Pay (Workers Comp)',        category: 'Payroll-Workers Comp',         amount: 86.75 },
  { date: '04/14/2026', checkNum: '4076', description: 'Tire Outlet — Tire Purchase',          category: 'Inventory-Tires',              amount: 460.00 },
  { date: '04/14/2026', checkNum: '4077', description: 'GW — Labor',                           category: 'Labor/Subcontractors',         amount: 150.00 },
  { date: '04/15/2026', checkNum: '',     description: 'ADP Wage Pay — Payroll',               category: 'Payroll-Wages',                amount: 1976.32 },
  { date: '04/16/2026', checkNum: '',     description: 'TAPCO Insurance — Business Insurance', category: 'Insurance-Business',           amount: 1138.82 },
  { date: '04/16/2026', checkNum: '',     description: 'TimePaymentcorp — Equipment Lease',    category: 'Equipment Lease',              amount: 741.95 },
  { date: '04/16/2026', checkNum: '4078', description: 'Tire Parts — Parts Purchase',          category: 'Inventory-Parts & Supplies',   amount: 152.31 },
  { date: '04/17/2026', checkNum: '',     description: 'ADP Payroll Processing Fee',           category: 'Payroll-Processing Fees',      amount: 134.50 },
  { date: '04/17/2026', checkNum: '',     description: 'Gladly Coffee',                        category: 'Meals/Entertainment',          amount: 27.32 },
  { date: '04/20/2026', checkNum: '',     description: 'ADP Wage Pay — Payroll',               category: 'Payroll-Wages',                amount: 1976.32 },
  { date: '04/20/2026', checkNum: '',     description: 'ADP Tax Deposit',                      category: 'Payroll-Payroll Taxes',        amount: 607.68 },
  { date: '04/20/2026', checkNum: '4079', description: 'Tire Co — Tire Purchase',              category: 'Inventory-Tires',              amount: 771.70 },
  { date: '04/21/2026', checkNum: '',     description: 'ADP 401k Contribution',                category: 'Payroll-401k',                 amount: 30.00 },
  { date: '04/21/2026', checkNum: '',     description: 'ADP Pay-By-Pay (Workers Comp)',        category: 'Payroll-Workers Comp',         amount: 86.75 },
  { date: '04/21/2026', checkNum: '',     description: 'ADP Tax Deposit',                      category: 'Payroll-Payroll Taxes',        amount: 607.68 },
  { date: '04/22/2026', checkNum: '4080', description: 'U.S. Auto Force — Parts',              category: 'Inventory-Parts & Supplies',   amount: 153.76 },
  { date: '04/22/2026', checkNum: '4081', description: 'Tireco — Tire Purchase',               category: 'Inventory-Tires',              amount: 318.80 },
  { date: '04/23/2026', checkNum: '4082', description: 'Tire Outlet — Tire Purchase',          category: 'Inventory-Tires',              amount: 400.00 },
  { date: '04/24/2026', checkNum: '',     description: 'ADP Payroll Processing Fee',           category: 'Payroll-Processing Fees',      amount: 134.50 },
  { date: '04/27/2026', checkNum: '',     description: 'ADP Wage Pay — Payroll',               category: 'Payroll-Wages',                amount: 1976.32 },
  { date: '04/27/2026', checkNum: '',     description: 'ADP Tax Deposit',                      category: 'Payroll-Payroll Taxes',        amount: 607.68 },
  { date: '04/27/2026', checkNum: '',     description: 'Gladly Coffee',                        category: 'Meals/Entertainment',          amount: 5.39 },
  { date: '04/27/2026', checkNum: '4083', description: 'Tire Network — Tire Purchase',         category: 'Inventory-Tires',              amount: 120.00 },
  { date: '04/28/2026', checkNum: '',     description: 'ADP 401k Contribution',                category: 'Payroll-401k',                 amount: 30.00 },
  { date: '04/28/2026', checkNum: '',     description: 'ADP Pay-By-Pay (Workers Comp)',        category: 'Payroll-Workers Comp',         amount: 86.75 },
  { date: '04/28/2026', checkNum: '',     description: 'Snapdragon Stadium',                   category: 'Meals/Entertainment',          amount: 35.56 },
  { date: '04/28/2026', checkNum: '4085', description: 'Tire Network — Tire Purchase',         category: 'Inventory-Tires',              amount: 228.00 },
  { date: '04/29/2026', checkNum: '',     description: 'SANDAG FasTrak — Toll',                category: 'Transportation',               amount: 2.50 },
  { date: '04/29/2026', checkNum: '',     description: 'APG Wholesale — Parts',                category: 'Inventory-Parts & Supplies',   amount: 415.80 },
  { date: '04/29/2026', checkNum: '',     description: 'BMW El Cajon — Vehicle Repair',        category: 'Vehicle-Repairs',              amount: 133.52 },
  { date: '04/29/2026', checkNum: '4071', description: 'Bureau of Auto Repair — License',      category: 'Licenses/Permits',             amount: 250.00 },
  { date: '04/29/2026', checkNum: '4087', description: 'Tire Co — Tire Purchase',              category: 'Inventory-Tires',              amount: 276.84 },
  { date: '04/30/2026', checkNum: '4088', description: 'U.S. Auto Force — Parts',              category: 'Inventory-Parts & Supplies',   amount: 786.00 },
  { date: '04/30/2026', checkNum: '4092', description: 'Owner Draw — Francisco Reyes',         category: 'Owner Draw',                   amount: 700.00 },
]

export const ccTransactions: CCTx[] = [
  { postDate: '04/01/2026', txDate: '04/01/2026', account: '...0214', description: 'SDFC Team Gym',          category: 'Personal - Gym',                   amount: 46.08,  personal: true  },
  { postDate: '04/03/2026', txDate: '04/02/2026', account: '...0214', description: 'Apple.com',               category: 'Personal - Subscriptions',         amount: 9.99,   personal: true  },
  { postDate: '04/05/2026', txDate: '04/04/2026', account: '...0214', description: 'SDFC Team Gym',          category: 'Personal - Gym',                   amount: 503.79, personal: true  },
  { postDate: '04/06/2026', txDate: '04/05/2026', account: '...0214', description: 'Amazon Digital',         category: 'Personal - Subscriptions',         amount: 12.99,  personal: true  },
  { postDate: '04/07/2026', txDate: '04/06/2026', account: '...0214', description: 'Amazon Digital',         category: 'Personal - Subscriptions',         amount: 2.99,   personal: true  },
  { postDate: '04/08/2026', txDate: '04/07/2026', account: '...0214', description: 'Amazon Prime',           category: 'Personal - Subscriptions',         amount: 16.15,  personal: true  },
  { postDate: '04/09/2026', txDate: '04/08/2026', account: '...0214', description: 'ESPN+',                  category: 'Personal - Subscriptions',         amount: 19.99,  personal: true  },
  { postDate: '04/10/2026', txDate: '04/09/2026', account: '...0214', description: 'Apple.com',               category: 'Personal - Subscriptions',         amount: 22.98,  personal: true  },
  { postDate: '04/11/2026', txDate: '04/10/2026', account: '...0214', description: 'Amazon Digital',         category: 'Personal - Subscriptions',         amount: 16.99,  personal: true  },
  { postDate: '04/12/2026', txDate: '04/11/2026', account: '...0214', description: 'Amazon Digital',         category: 'Personal - Subscriptions',         amount: 2.99,   personal: true  },
  { postDate: '04/14/2026', txDate: '04/13/2026', account: '...0214', description: 'SDFC Team Gym',          category: 'Personal - Gym',                   amount: 432.33, personal: true  },
  { postDate: '04/15/2026', txDate: '04/14/2026', account: '...0214', description: 'Amazon Digital',         category: 'Personal - Subscriptions',         amount: 19.99,  personal: true  },
  { postDate: '04/18/2026', txDate: '04/17/2026', account: '...0214', description: 'Cox Communications',     category: 'Utilities - Internet',             amount: 110.17, personal: false },
  { postDate: '04/20/2026', txDate: '04/19/2026', account: '...0214', description: 'Infinity Kat',           category: 'Miscellaneous (Review)',           amount: 400.60, personal: false },
  { postDate: '04/22/2026', txDate: '04/21/2026', account: '...0214', description: 'A to Z Tax Firm',        category: 'Professional Services - Tax Prep', amount: 420.00, personal: false },
  { postDate: '04/30/2026', txDate: '04/30/2026', account: '...0214', description: 'Finance Charge',         category: 'Finance Charges',                  amount: 63.07,  personal: false },
  { postDate: '04/30/2026', txDate: '04/30/2026', account: '...0539', description: 'Finance Charge',         category: 'Finance Charges',                  amount: 51.72,  personal: false },
  { postDate: '04/15/2026', txDate: '04/14/2026', account: '...6514', description: 'ADT Security Services',  category: 'Security System',                  amount: 98.08,  personal: false },
  { postDate: '04/30/2026', txDate: '04/30/2026', account: '...6514', description: 'Finance Charge',         category: 'Finance Charges',                  amount: 96.97,  personal: false },
]
